Stop duplicating properties in favour of using bosh link
[#165861393]

diff --git a/jobs/bbr-smbbroker/templates/post-restore-unlock.sh.erb b/jobs/bbr-smbbroker/templates/post-restore-unlock.sh.erb
--- a/jobs/bbr-smbbroker/templates/post-restore-unlock.sh.erb
+++ b/jobs/bbr-smbbroker/templates/post-restore-unlock.sh.erb
@@ -1,36 +1,37 @@
 #!/usr/bin/env bash
 
-set -ex
+set -euo pipefail
+set -x
 
-PATH="/var/vcap/packages/cf-cli-6-linux/bin:$PATH"
+PATH="/var/vcap/packages/cf-cli-6-linux/bin:${PATH}"
 
-API_ENDPOINT=https://api.<%= p('domain') %>
-ORG=<%= p('organization') %>
-SPACE=<%= p('space') %>
-APP_NAME=<%= p('app_name') %>
+API_ENDPOINT=https://api.<%= link('smbbrokerpush').p('domain') %>
+ORG=<%= link('smbbrokerpush').p('organization') %>
+SPACE=<%= link('smbbrokerpush').p('space') %>
+APP_NAME=<%= link('smbbrokerpush').p('app_name') %>
 
 function cf_auth_and_target() {
 	echo "Authenticate and target..."
 
-	cf api $API_ENDPOINT <% if p('skip_cert_verify') %>--skip-ssl-validation<% end %>
+	cf api $API_ENDPOINT <% if link('smbbrokerpush').p('skip_cert_verify') %>--skip-ssl-validation<% end %>
 
-    set +x
-	<% if_p('cf.client_id', 'cf.client_secret') do |client_id, client_secret| %>
+	set +x
+    <% link('smbbrokerpush').if_p('cf.client_id', 'cf.client_secret') do |client_id, client_secret| %>
         cf auth "<%= client_id %>" "<%= client_secret %>" --client-credentials
     <% end.else do %>
-        cf auth "<%= p('cf.admin_user') %>" "<%= p('cf.admin_password') %>"
+        cf auth "<%= link('smbbrokerpush').p('cf.admin_user') %>" "<%= link('smbbrokerpush').p('cf.admin_password') %>"
     <% end %>
 	set -x
 	echo -e  "********************\n"
 
 	if ! cf target -o $ORG -s $SPACE ; then
-		echo "org '$ORG' with space '$SPACE' not found; exiting"
-		exit 0
+	    echo "org '${ORG}' with space '${SPACE}' not found; exiting"
+	    exit 0
 	fi
 
 	if ! cf app $APP_NAME ; then
-		echo "'$APP_NAME' app not deployed; exiting"
-		exit 0
+	    echo "'${APP_NAME}' app not deployed; exiting"
+	    exit 0
 	fi
 }
 
